- name: Roboshop App Playbook
  hosts: all
  become: yes
  roles:
    - "{{ app_name }}"




#. Hee in the above msg line , we have the value starting with a string URL,
  # msg: " {{ URL }} , Must and should double quote if the value starts with variable in ansible